### PR TITLE
Add 400G value_transform

### PR DESCRIPTION
**Pull request by camrossi**
Adding 400G interface support in the example config

### CODE REVIEW

**Review by thenodon — COMMENTED** [review]
@camrossi thanks for the PR. Just like to understand what this adds to the example config file. Its just an example that hopefully lets people get started.

**Comment by thenodon** [comment]
I have added the row to the example-config.yml in branch issue_22 and will be in the next release.

**Comment by camrossi** [comment]
Yes was just adding the 400G line in the example file, nothing more. 
In my environment I had 400G enabled switches and I was getting errors in the container logs

**Comment by thenodon** [comment]
Since the example is update in branch issue_22 I will close this PR

**Pull request closed without merging**
